AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  CombinationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: br.com.at.lambda.combination.handler.CombinationHandler::handleRequest
      Runtime: java8
      Timeout: 40
      Events:
        Combination:
          Type: Api
          Properties:
            Path: /combination
            Method: POST
